/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read application readiness */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/topics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published topics */
    get: operations["listTopics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/topics/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one published topic */
    get: operations["getTopic"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a simulation descriptor */
    get: operations["getSimulation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/{id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run one bounded deterministic simulation
     * @description Simulation delivery uses process-local admission before body parsing (default two active requests across models), a bounded raw body, and bounded serialization of the entire result (default 4 MiB). These HTTP safeguards are outside modeled behavior. No queued or automatic retry is added; an admitted run keeps its existing model/schema semantics.
     */
    post: operations["runSimulation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimators/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a capacity estimator descriptor */
    get: operations["getEstimator"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimators/{id}/calculations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Calculate a bounded capacity estimate */
    post: operations["calculateEstimate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/distributed-rate-limiter": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the distributed rate limiter descriptor */
    get: operations["getRateLimiterSimulation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/distributed-rate-limiter/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run one deterministic rate limiter simulation
     * @description Simulation delivery uses process-local admission before body parsing (default two active requests across models), a bounded raw body, and bounded serialization of the entire result (default 4 MiB). These HTTP safeguards are outside modeled behavior. No queued or automatic retry is added; an admitted run keeps its existing model/schema semantics.
     */
    post: operations["runRateLimiterSimulation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/cache-aside": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the cache-aside simulation descriptor */
    get: operations["getCacheAsideSimulation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/cache-aside/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run one deterministic cache-aside simulation
     * @description Simulation delivery uses process-local admission before body parsing (default two active requests across models), a bounded raw body, and bounded serialization of the entire result (default 4 MiB). These HTTP safeguards are outside modeled behavior. No queued or automatic retry is added; an admitted run keeps its existing model/schema semantics.
     */
    post: operations["runCacheAsideSimulation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/case-studies/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read a draft or published design workshop by explicit ID
     * @description Draft workshops are accessible by direct link, excluded from ordinary published discovery. This endpoint serves educational content; it creates no short links.
     */
    get: operations["getCaseStudy"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/case-studies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List published case studies
     * @description Published, startup-validated case-study metadata in catalog order, then ID. Draft and planned entries are omitted. Returns an empty array when none are published. Explicit draft detail routes remain available.
     */
    get: operations["listCaseStudies"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search published concepts and workshop stages
     * @description Packaged public content only. Literal terms must all occur in title, summary or plain body text. Title matches precede summary then body; ties use catalog order and stable IDs, preserving workshop stage order. Draft/planned content and learner answers are excluded. Unknown/repeated filters return 400. Returns at most 20 results with the total match count.
     */
    get: operations["searchPublishedContent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/learning-paths/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read an ordered learning path with published destinations and current answer identities */
    get: operations["getLearningPath"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @constant */
      status: "ready";
    };
    CatalogEntry: {
      id: string;
      /** @enum {string} */
      kind: "topic" | "case-study";
      title: string;
      summary: string;
      category: string;
      level: string;
      order: number;
      /** @enum {string} */
      status: "draft" | "published";
      prerequisites: string[];
      outcomes: string[];
      capabilities: (
        | "study"
        | "simulation"
        | "estimator"
        | "case-study"
        | "practice"
        | "guided"
      )[];
      lessonPath?: string;
      questionsPath?: string;
      resourcesPath: string;
      /** @description Present only with the guided capability. */
      checkpointsPath?: string;
      simulationIds: string[];
      estimatorIds: string[];
      contentVersion: string;
      /** Format: date */
      reviewedAt: string;
      sourceIds: string[];
      /** @description Present for authored case-study entries; absent for topics. */
      workshopPath?: string;
    };
    QuestionOption: {
      id: string;
      label: string;
      distractorExplanation?: string;
    };
    Question: {
      id: string;
      topicId: string;
      /** @enum {string} */
      level: "beginner" | "intermediate" | "advanced";
      /** @enum {string} */
      kind:
        | "recall"
        | "prediction"
        | "diagnosis"
        | "design-decision"
        | "calculation";
      prompt: string;
      options?: components["schemas"]["QuestionOption"][];
      correctOptionId?: string;
      explanation?: string;
      followUp?: string;
      rubric?: string[];
      modelAnswer?: string;
      sourceIds?: string[];
    };
    TopicDetail: {
      topic: components["schemas"]["CatalogEntry"];
      lessonMarkdown: string;
      questions: components["schemas"]["Question"][];
      /** @description Guided simulation checkpoints; empty unless the topic has the guided capability. */
      checkpoints: components["schemas"]["GuidedCheckpoint"][];
    };
    /** @description One predict -> reveal -> explain -> choose step. target names one event in the preset's Java trace by operation, kind, and occurrence. */
    GuidedCheckpoint: {
      id: string;
      title: string;
      simulationId: string;
      presetId: string;
      target: {
        operation: number;
        kind: string;
        occurrence: number;
      };
      prompt: string;
      lookFor: string;
      explanation: string;
      tradeoff: {
        prompt: string;
        options: {
          id: string;
          label: string;
          feedback: string;
        }[];
        recommendedOptionId: string;
      };
    };
    RequestFlowInput: {
      /** @constant */
      schemaVersion: "1.0";
      /** @enum {string} */
      modelVersion: "1.0.0" | "1.1.1";
      /** @enum {string} */
      policy: "ROUND_ROBIN" | "LEAST_OUTSTANDING";
      arrivalTimesMs: number[];
      nodeServiceTimesMs: number[];
      workersPerNode: number;
      queueCapacity: number;
      /** @description Optional failure schedule for model version 1.1.1. Not allowed with model version 1.0.0. */
      failureSchedule?: components["schemas"]["FailureScheduleEntry"][] | null;
      /** Format: int64 */
      seed: number;
    };
    SimulationPreset: {
      id: string;
      title: string;
      question: string;
      input: components["schemas"]["RequestFlowInput"];
    };
    SimulationDescriptor: {
      /** @constant */
      id: "request-flow";
      title: string;
      /** @constant */
      kind: "simulation";
      /** @enum {string} */
      modelVersion: "1.0.0" | "1.1.1";
      description: string;
      limits: components["schemas"]["SimulationLimits"];
      presets: components["schemas"]["SimulationPreset"][];
      assumptions: string[];
    };
    SimulationEvent: {
      sequence: number;
      /** Format: int64 */
      timeMs: number;
      /** @enum {string} */
      kind:
        | "request.arrived"
        | "request.routed"
        | "request.queued"
        | "request.started"
        | "request.completed"
        | "request.rejected"
        | "request.failed"
        | "node.failed"
        | "node.recovered";
      requestId: string | null;
      nodeId: string | null;
      message: string;
    };
    RequestOutcome: {
      requestId: string;
      nodeId: string | null;
      /** @enum {string} */
      status: "COMPLETED" | "REJECTED" | "FAILED";
      /** Format: int64 */
      arrivalMs: number;
      /** Format: int64 */
      startMs: number | null;
      /** Format: int64 */
      completionMs: number | null;
      /** Format: int64 */
      queueMs: number | null;
      /** Format: int64 */
      serviceMs: number | null;
      /** Format: int64 */
      latencyMs: number | null;
    };
    RequestFlowMetrics: {
      completed: number;
      rejected: number;
      failed: number;
      meanLatencyMs: number | null;
      /** Format: int64 */
      p95LatencyMs: number | null;
      throughputPerSecond: number | null;
      /** Format: int64 */
      observationWindowMs: number;
    };
    RequestFlowResult: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      simulationId: "request-flow";
      /** @enum {string} */
      modelVersion: "1.0.0" | "1.1.1";
      /** Format: int64 */
      seed: number;
      /** @enum {string} */
      status: "completed" | "limited";
      assumptions: string[];
      events: components["schemas"]["SimulationEvent"][];
      outcomes: components["schemas"]["RequestOutcome"][];
      metrics: components["schemas"]["RequestFlowMetrics"];
      /** @enum {string|null} */
      truncationReason?:
        | "event_limit"
        | "virtual_time_limit"
        | "trace_size_limit"
        | "wall_time_limit"
        | null;
      /** Format: int64 */
      lastVirtualTimeMs: number;
      incompleteRequests: number;
      limits: components["schemas"]["SimulationLimits"];
    };
    ApiError: {
      code: string;
      message: string;
      fieldErrors: {
        [key: string]: string;
      };
      /**
       * Format: date-time
       * @description Server error time; external metadata, excluded from simulation replay.
       */
      timestamp: string;
    };
    CapacityEstimateInput: {
      /** @constant */
      schemaVersion: "1.0";
      /** Format: int64 */
      dailyActiveUsers: number;
      requestsPerUserPerDay: number;
      peakFactor: number;
      readPercentage: number;
      recordSizeKb: number;
      responseSizeKb: number;
      retentionDays: number;
      replicationFactor: number;
      meanLatencyMs: number;
      headroomPercentage: number;
    };
    CapacityMetrics: {
      dailyRequests: number;
      averageRequestsPerSecond: number;
      peakRequestsPerSecond: number;
      peakReadsPerSecond: number;
      peakWritesPerSecond: number;
      dailyWrites: number;
      rawStorageGigabytes: number;
      replicatedStorageGigabytes: number;
      dailyResponseGigabytes: number;
      peakResponseMegabitsPerSecond: number;
      meanConcurrentRequests: number;
      peakRequestsWithHeadroom: number;
    };
    CalculationStep: {
      id: string;
      label: string;
      formula: string;
      unit: string;
      meaning: string;
      value: number;
    };
    SensitivityPoint: {
      id: string;
      label: string;
      trafficMultiplier: number;
      peakRequestsPerSecond: number;
      peakResponseMegabitsPerSecond: number;
      meanConcurrentRequests: number;
    };
    CapacityEstimateResult: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      estimatorId: "capacity-estimation";
      /** @constant */
      status: "estimated";
      metrics: components["schemas"]["CapacityMetrics"];
      steps: components["schemas"]["CalculationStep"][];
      sensitivity: components["schemas"]["SensitivityPoint"][];
      assumptions: string[];
      warnings: string[];
    };
    CapacityEstimatorPreset: {
      id: string;
      title: string;
      question: string;
      input: components["schemas"]["CapacityEstimateInput"];
    };
    CapacityEstimatorDescriptor: {
      /** @constant */
      id: "capacity-estimation";
      title: string;
      /** @constant */
      kind: "estimator";
      /** @constant */
      schemaVersion: "1.0";
      description: string;
      defaultInput: components["schemas"]["CapacityEstimateInput"];
      presets: components["schemas"]["CapacityEstimatorPreset"][];
      limits: {
        [key: string]: unknown;
      };
      assumptions: string[];
    };
    SimulationLimits: {
      maxRequests: number;
      maxNodes: number;
      maxWorkersPerNode: number;
      maxQueueCapacity: number;
      maxEvents: number;
      /** Format: int64 */
      maxVirtualTimeMs: number;
      /** Format: int64 */
      maxArrivalTimeMs: number;
      /** Format: int64 */
      maxServiceTimeMs: number;
    };
    RateLimiterInput: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      modelVersion: "1.0.0";
      /** @enum {string} */
      algorithm: "FIXED_WINDOW" | "TOKEN_BUCKET";
      /** @enum {string} */
      counterScope: "SHARED" | "LOCAL_PER_NODE";
      nodeCount: number;
      limit: number;
      /** Format: int64 */
      windowMs: number;
      refillTokensPerSecond: number;
      counterBackendAvailable: boolean;
      /** @enum {string} */
      backendFailurePolicy: "FAIL_OPEN" | "FAIL_CLOSED";
      arrivalTimesMs: number[];
      /** Format: int64 */
      seed: number;
    };
    RateLimitEvent: {
      sequence: number;
      /** Format: int64 */
      timeMs: number;
      /** @enum {string} */
      kind:
        | "request.arrived"
        | "request.allowed"
        | "request.rejected"
        | "request.bypassed";
      requestId: string;
      nodeId: string;
      message: string;
    };
    RateLimitOutcome: {
      requestId: string;
      nodeId: string;
      /** Format: int64 */
      timeMs: number;
      /** @enum {string} */
      decision: "ALLOWED" | "REJECTED" | "BYPASSED";
      remaining: number;
      /** Format: int64 */
      retryAfterMs?: number | null;
      reason: string;
    };
    RateLimitMetrics: {
      total: number;
      allowed: number;
      rejected: number;
      bypassed: number;
      configuredLimit: number;
      counters: number;
      maximumAggregateAllowance: number;
    };
    RateLimiterResult: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      simulationId: "distributed-rate-limiter";
      /** @constant */
      modelVersion: "1.0.0";
      /** Format: int64 */
      seed: number;
      /** @constant */
      status: "completed";
      assumptions: string[];
      events: components["schemas"]["RateLimitEvent"][];
      outcomes: components["schemas"]["RateLimitOutcome"][];
      metrics: components["schemas"]["RateLimitMetrics"];
    };
    RateLimiterPreset: {
      id: string;
      title: string;
      question: string;
      input: components["schemas"]["RateLimiterInput"];
    };
    RateLimiterDescriptor: {
      /** @constant */
      id: "distributed-rate-limiter";
      title: string;
      /** @constant */
      kind: "simulation";
      /** @constant */
      modelVersion: "1.0.0";
      description: string;
      limits: {
        [key: string]: number;
      };
      presets: components["schemas"]["RateLimiterPreset"][];
      assumptions: string[];
    };
    FailureScheduleEntry: {
      /** @description Stable identifier of the entity that fails (e.g. Node A) */
      entityId: string;
      /**
       * Format: int64
       * @description Virtual time in milliseconds when the failure occurs
       */
      failAtMs: number;
      /**
       * Format: int64
       * @description Virtual time when the entity recovers; null means permanent failure for this run
       */
      recoverAtMs?: number | null;
      /**
       * @description What happens to work already assigned at failure time
       * @enum {string}
       */
      inFlightBehavior: "FAIL" | "COMPLETE";
    };
    CacheOperation: {
      /** @enum {string} */
      kind: "GET" | "UPDATE";
      key: string;
      value?: string | null;
      /** Format: int64 */
      timeMs: number;
    };
    CacheAsideInput: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      modelVersion: "1.0.1";
      /** Format: int64 */
      cacheLookupLatencyMs: number;
      /** Format: int64 */
      originReadLatencyMs: number;
      /** Format: int64 */
      ttlMs: number;
      initialOriginValue: string;
      operations: components["schemas"]["CacheOperation"][];
      cacheAvailable: boolean;
      originAvailable: boolean;
      /** Format: int64 */
      seed: number;
    };
    CacheGetOutcome: {
      key: string;
      returnedValue?: string | null;
      /**
       * @description ERROR means origin unavailable. A MISS or BYPASS with null returnedValue means key not found; absent keys are not cached.
       * @enum {string}
       */
      hitOrMiss: "HIT" | "MISS" | "BYPASS" | "ERROR";
      stale: boolean;
      /** Format: int64 */
      requestTimeMs: number;
      /** Format: int64 */
      responseTimeMs: number;
      /** Format: int64 */
      latencyMs: number;
    };
    CacheAsideMetrics: {
      totalGets: number;
      cacheHits: number;
      cacheMisses: number;
      staleReads: number;
      originReads: number;
      /** @description Hits divided by hits + misses observed in the trace; bypass excluded, failed misses included. Zero when no eligible lookup exists. */
      hitRatio: number;
      /** Format: int64 */
      observationWindowMs: number;
      cacheBypasses: number;
      failedGets: number;
    };
    CacheEntryState: {
      value: string;
      /**
       * Format: int64
       * @description Origin version the entry was filled from.
       */
      version: number;
      /** Format: int64 */
      filledAtMs: number;
      /**
       * Format: int64
       * @description A lookup at or after this time misses.
       */
      expiresAtMs: number;
    };
    OriginValueState: {
      value: string;
      /** Format: int64 */
      version: number;
    };
    /** @description State before the first event. The cache starts empty; availability is constant for the run. */
    CacheAsideInitialState: {
      cacheAvailable: boolean;
      originAvailable: boolean;
      origin: {
        key: string;
        value: string;
        /** Format: int64 */
        version: number;
      }[];
    };
    /** @description A trace event with the state of its key immediately after the event. Applying each event's key state over initialState reconstructs the full cache and origin state; never parse message. */
    CacheAsideEvent: {
      sequence: number;
      /** Format: int64 */
      timeMs: number;
      /** @enum {string} */
      kind:
        | "cache.hit"
        | "cache.miss"
        | "cache.fill"
        | "cache.bypass"
        | "cache.error"
        | "origin.read"
        | "origin.update"
        | "origin.error";
      /** @description The operation the event belongs to, as "Operation N" in input order. */
      requestId: string;
      /** @enum {string} */
      nodeId: "cache" | "origin";
      message: string;
      /** @description 1-based position of the operation in the submitted input. */
      operation: number;
      /** @description The cache key the event applies to. */
      key: string;
      /** @description The key's cache entry after this event; absent when the cache holds no entry. */
      cacheEntry?: components["schemas"]["CacheEntryState"];
      /** @description The key's committed origin value after this event; absent when the origin has no such key. */
      originValue?: components["schemas"]["OriginValueState"];
    };
    CacheAsideResult: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      simulationId: "cache-aside";
      /** @constant */
      modelVersion: "1.0.1";
      /** Format: int64 */
      seed: number;
      /** @enum {string} */
      status: "completed" | "limited";
      /** @enum {string|null} */
      truncationReason?:
        | "event_limit"
        | "virtual_time_limit"
        | "trace_size_limit"
        | "wall_time_limit"
        | null;
      /** Format: int64 */
      lastVirtualTimeMs: number;
      assumptions: string[];
      initialState: components["schemas"]["CacheAsideInitialState"];
      events: components["schemas"]["CacheAsideEvent"][];
      outcomes: components["schemas"]["CacheGetOutcome"][];
      metrics: components["schemas"]["CacheAsideMetrics"];
      incompleteGets: number;
    };
    CacheAsidePreset: {
      id: string;
      title: string;
      question: string;
      input: components["schemas"]["CacheAsideInput"];
    };
    /** @description Exact input bounds the Java model enforces. Clients validate against these instead of repeating them. */
    CacheAsideLimits: {
      /**
       * Format: int64
       * @description Largest cache lookup or origin read latency, in milliseconds.
       */
      maxLatencyMs: number;
      /**
       * Format: int64
       * @description Largest TTL, in milliseconds.
       */
      maxTtlMs: number;
      /** @description Largest number of operations in one run. */
      maxOperations: number;
      /**
       * Format: int64
       * @description Latest operation arrival time, in milliseconds.
       */
      maxOperationTimeMs: number;
      /** @description Longest cache key, in characters. */
      maxKeyLength: number;
      /** @description Longest initial or updated value, in characters. */
      maxValueLength: number;
    };
    CacheAsideDescriptor: {
      /** @constant */
      id: "cache-aside";
      title: string;
      /** @constant */
      kind: "simulation";
      /** @constant */
      modelVersion: "1.0.1";
      description: string;
      limits: components["schemas"]["CacheAsideLimits"];
      presets: components["schemas"]["CacheAsidePreset"][];
      assumptions: string[];
    };
    RubricCriterion: {
      id: string;
      prompt: string;
    };
    ExperimentLink: {
      topicId: string;
      label: string;
      instruction: string;
    };
    WorkshopStage: {
      id: string;
      title: string;
      prompt: string;
      reference: string;
      rubric: components["schemas"]["RubricCriterion"][];
      experimentLinks: components["schemas"]["ExperimentLink"][];
      sourceIds: string[];
      walkthroughs?: components["schemas"]["WorkshopWalkthrough"][];
    };
    Workshop: {
      /** @constant */
      schemaVersion: 1;
      id: string;
      contentVersion: string;
      introduction: string;
      invariant: string;
      stages: components["schemas"]["WorkshopStage"][];
    };
    CaseStudyDetail: {
      entry: components["schemas"]["CatalogEntry"];
      workshop: components["schemas"]["Workshop"];
    };
    WorkshopNode: {
      id: string;
      title: string;
      detail: string;
    };
    WorkshopStep: {
      id: string;
      title: string;
      from: string;
      to: string;
      detail: string;
    };
    WorkshopWalkthrough: {
      id: string;
      title: string;
      summary: string;
      nodes: components["schemas"]["WorkshopNode"][];
      steps: components["schemas"]["WorkshopStep"][];
    };
    SearchHit: {
      entry: components["schemas"]["CatalogEntry"];
      stageId?: string;
      stageTitle?: string;
      path: string;
      excerpt: string;
    };
    SearchResponse: {
      /** @constant */
      schemaVersion: 1;
      query: string;
      results: components["schemas"]["SearchHit"][];
      totalMatches: number;
      /** @constant */
      limit: 20;
    };
    LearningActivity: {
      id: string;
      /** @enum {string} */
      kind: "text" | "choice";
      optionIds: string[];
    };
    LearningPathStep: {
      moduleId: string;
      purpose: string;
      available: boolean;
      entry?: components["schemas"]["CatalogEntry"];
      activities: components["schemas"]["LearningActivity"][];
    };
    LearningPath: {
      /** @constant */
      schemaVersion: 1;
      id: string;
      title: string;
      summary: string;
      steps: components["schemas"]["LearningPathStep"][];
      optionalModules: components["schemas"]["CatalogEntry"][];
    };
  };
  responses: never;
  parameters: {
    ContentId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  listTopics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogEntry"][];
        };
      };
    };
  };
  getTopic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TopicDetail"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimulationDescriptor"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  runSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestFlowInput"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RequestFlowResult"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description request_too_large: raw API POST body exceeds the configured byte limit (default 256 KiB), including unknown-length/chunked bodies. No model executes. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description result_too_large: complete serialized result exceeds the response limit. A structured error replaces the result; no partial successful JSON is sent. Reduce workload before retrying. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description simulation_busy: all process-local run slots are occupied. Try again explicitly after the Retry-After hint; it does not guarantee capacity is free. */
      503: {
        headers: {
          /** @description Retry hint in seconds. Capacity may remain occupied. */
          "Retry-After"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getEstimator: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CapacityEstimatorDescriptor"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  calculateEstimate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CapacityEstimateInput"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CapacityEstimateResult"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description request_too_large: raw API POST body exceeds the configured byte limit (default 256 KiB), including unknown-length/chunked bodies. No model executes. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getRateLimiterSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RateLimiterDescriptor"];
        };
      };
    };
  };
  runRateLimiterSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RateLimiterInput"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RateLimiterResult"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description request_too_large: raw API POST body exceeds the configured byte limit (default 256 KiB), including unknown-length/chunked bodies. No model executes. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description result_too_large: complete serialized result exceeds the response limit. A structured error replaces the result; no partial successful JSON is sent. Reduce workload before retrying. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description simulation_busy: all process-local run slots are occupied. Try again explicitly after the Retry-After hint; it does not guarantee capacity is free. */
      503: {
        headers: {
          /** @description Retry hint in seconds. Capacity may remain occupied. */
          "Retry-After"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getCacheAsideSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CacheAsideDescriptor"];
        };
      };
    };
  };
  runCacheAsideSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CacheAsideInput"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CacheAsideResult"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description request_too_large: raw API POST body exceeds the configured byte limit (default 256 KiB), including unknown-length/chunked bodies. No model executes. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description result_too_large: complete serialized result exceeds the response limit. A structured error replaces the result; no partial successful JSON is sent. Reduce workload before retrying. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description simulation_busy: all process-local run slots are occupied. Try again explicitly after the Retry-After hint; it does not guarantee capacity is free. */
      503: {
        headers: {
          /** @description Retry hint in seconds. Capacity may remain occupied. */
          "Retry-After"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getCaseStudy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versioned workshop content */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseStudyDetail"];
        };
      };
      /** @description No authored case study with this ID */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  listCaseStudies: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogEntry"][];
        };
      };
    };
  };
  searchPublishedContent: {
    parameters: {
      query?: {
        /** @description Blank returns no results; otherwise 2–100 UTF-16 code units. Searches all whitespace-separated terms as literal substrings, ignoring case and compatibility character forms. */
        q?: string;
        /** @description Optional catalog level. */
        level?: "" | "Beginner" | "Intermediate" | "Advanced";
        /** @description Optional declared learning activity. */
        capability?:
          | ""
          | "study"
          | "simulation"
          | "estimator"
          | "case-study"
          | "practice"
          | "guided";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bounded search results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getLearningPath: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Validated path; unpublished steps have no entry or activity metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LearningPath"];
        };
      };
      /** @description No learning path with this ID */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
}
