/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read application readiness */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/topics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published topics */
    get: operations["listTopics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/topics/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one published topic */
    get: operations["getTopic"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a simulation descriptor */
    get: operations["getSimulation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/{id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run one bounded deterministic simulation */
    post: operations["runSimulation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimators/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a capacity estimator descriptor */
    get: operations["getEstimator"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimators/{id}/calculations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Calculate a bounded capacity estimate */
    post: operations["calculateEstimate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/distributed-rate-limiter": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the distributed rate limiter descriptor */
    get: operations["getRateLimiterSimulation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/simulations/distributed-rate-limiter/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run one deterministic rate limiter simulation */
    post: operations["runRateLimiterSimulation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @constant */
      status: "ready";
    };
    CatalogEntry: {
      id: string;
      /** @enum {string} */
      kind: "topic" | "case-study";
      title: string;
      summary: string;
      category: string;
      level: string;
      order: number;
      /** @enum {string} */
      status: "published";
      prerequisites: string[];
      outcomes: string[];
      capabilities: (
        "study" | "simulation" | "estimator" | "case-study" | "practice"
      )[];
      lessonPath: string;
      questionsPath: string;
      resourcesPath: string;
      simulationIds: string[];
      estimatorIds: string[];
      contentVersion: string;
      /** Format: date */
      reviewedAt: string;
      sourceIds: string[];
    };
    QuestionOption: {
      id: string;
      label: string;
      distractorExplanation?: string;
    };
    Question: {
      id: string;
      topicId: string;
      /** @enum {string} */
      level: "beginner" | "intermediate" | "advanced";
      /** @enum {string} */
      kind:
        | "recall"
        | "prediction"
        | "diagnosis"
        | "design-decision"
        | "calculation";
      prompt: string;
      options?: components["schemas"]["QuestionOption"][];
      correctOptionId?: string;
      explanation?: string;
      followUp?: string;
      rubric?: string[];
      modelAnswer?: string;
      sourceIds?: string[];
    };
    TopicDetail: {
      topic: components["schemas"]["CatalogEntry"];
      lessonMarkdown: string;
      questions: components["schemas"]["Question"][];
    };
    RequestFlowInput: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      modelVersion: "1.0.0";
      /** @enum {string} */
      policy: "ROUND_ROBIN" | "LEAST_OUTSTANDING";
      arrivalTimesMs: number[];
      nodeServiceTimesMs: number[];
      workersPerNode: number;
      queueCapacity: number;
      /** Format: int64 */
      seed: number;
    };
    SimulationPreset: {
      id: string;
      title: string;
      question: string;
      input: components["schemas"]["RequestFlowInput"];
    };
    SimulationDescriptor: {
      /** @constant */
      id: "request-flow";
      title: string;
      /** @constant */
      kind: "simulation";
      /** @constant */
      modelVersion: "1.0.0";
      description: string;
      limits: components["schemas"]["SimulationLimits"];
      presets: components["schemas"]["SimulationPreset"][];
      assumptions: string[];
    };
    SimulationEvent: {
      sequence: number;
      /** Format: int64 */
      timeMs: number;
      /** @enum {string} */
      kind:
        | "request.arrived"
        | "request.routed"
        | "request.queued"
        | "request.started"
        | "request.completed"
        | "request.rejected";
      requestId: string | null;
      nodeId: string | null;
      message: string;
    };
    RequestOutcome: {
      requestId: string;
      nodeId: string;
      /** @enum {string} */
      status: "COMPLETED" | "REJECTED";
      /** Format: int64 */
      arrivalMs: number;
      /** Format: int64 */
      startMs: number | null;
      /** Format: int64 */
      completionMs: number | null;
      /** Format: int64 */
      queueMs: number | null;
      /** Format: int64 */
      serviceMs: number | null;
      /** Format: int64 */
      latencyMs: number | null;
    };
    RequestFlowMetrics: {
      completed: number;
      rejected: number;
      meanLatencyMs: number | null;
      /** Format: int64 */
      p95LatencyMs: number | null;
      throughputPerSecond: number | null;
      /** Format: int64 */
      observationWindowMs: number;
    };
    RequestFlowResult: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      simulationId: "request-flow";
      /** @constant */
      modelVersion: "1.0.0";
      /** Format: int64 */
      seed: number;
      /** @enum {string} */
      status: "completed" | "limited";
      assumptions: string[];
      events: components["schemas"]["SimulationEvent"][];
      outcomes: components["schemas"]["RequestOutcome"][];
      metrics: components["schemas"]["RequestFlowMetrics"];
      /** @enum {string|null} */
      truncationReason?: "event_limit" | "virtual_time_limit" | null;
      /** Format: int64 */
      lastVirtualTimeMs: number;
      incompleteRequests: number;
      limits: components["schemas"]["SimulationLimits"];
    };
    ApiError: {
      code: string;
      message: string;
      fieldErrors: {
        [key: string]: string;
      };
    };
    CapacityEstimateInput: {
      /** @constant */
      schemaVersion: "1.0";
      /** Format: int64 */
      dailyActiveUsers: number;
      requestsPerUserPerDay: number;
      peakFactor: number;
      readPercentage: number;
      recordSizeKb: number;
      responseSizeKb: number;
      retentionDays: number;
      replicationFactor: number;
      meanLatencyMs: number;
      headroomPercentage: number;
    };
    CapacityMetrics: {
      dailyRequests: number;
      averageRequestsPerSecond: number;
      peakRequestsPerSecond: number;
      peakReadsPerSecond: number;
      peakWritesPerSecond: number;
      dailyWrites: number;
      rawStorageGigabytes: number;
      replicatedStorageGigabytes: number;
      dailyResponseGigabytes: number;
      peakResponseMegabitsPerSecond: number;
      meanConcurrentRequests: number;
      peakRequestsWithHeadroom: number;
    };
    CalculationStep: {
      id: string;
      label: string;
      formula: string;
      unit: string;
      meaning: string;
      value: number;
    };
    SensitivityPoint: {
      id: string;
      label: string;
      trafficMultiplier: number;
      peakRequestsPerSecond: number;
      peakResponseMegabitsPerSecond: number;
      meanConcurrentRequests: number;
    };
    CapacityEstimateResult: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      estimatorId: "capacity-estimation";
      /** @constant */
      status: "estimated";
      metrics: components["schemas"]["CapacityMetrics"];
      steps: components["schemas"]["CalculationStep"][];
      sensitivity: components["schemas"]["SensitivityPoint"][];
      assumptions: string[];
      warnings: string[];
    };
    CapacityEstimatorPreset: {
      id: string;
      title: string;
      question: string;
      input: components["schemas"]["CapacityEstimateInput"];
    };
    CapacityEstimatorDescriptor: {
      /** @constant */
      id: "capacity-estimation";
      title: string;
      /** @constant */
      kind: "estimator";
      /** @constant */
      schemaVersion: "1.0";
      description: string;
      defaultInput: components["schemas"]["CapacityEstimateInput"];
      presets: components["schemas"]["CapacityEstimatorPreset"][];
      limits: {
        [key: string]: unknown;
      };
      assumptions: string[];
    };
    SimulationLimits: {
      maxRequests: number;
      maxNodes: number;
      maxWorkersPerNode: number;
      maxQueueCapacity: number;
      maxEvents: number;
      /** Format: int64 */
      maxVirtualTimeMs: number;
      /** Format: int64 */
      maxArrivalTimeMs: number;
      /** Format: int64 */
      maxServiceTimeMs: number;
    };
    RateLimiterInput: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      modelVersion: "1.0.0";
      /** @enum {string} */
      algorithm: "FIXED_WINDOW" | "TOKEN_BUCKET";
      /** @enum {string} */
      counterScope: "SHARED" | "LOCAL_PER_NODE";
      nodeCount: number;
      limit: number;
      /** Format: int64 */
      windowMs: number;
      refillTokensPerSecond: number;
      counterBackendAvailable: boolean;
      /** @enum {string} */
      backendFailurePolicy: "FAIL_OPEN" | "FAIL_CLOSED";
      arrivalTimesMs: number[];
      /** Format: int64 */
      seed: number;
    };
    RateLimitEvent: {
      sequence: number;
      /** Format: int64 */
      timeMs: number;
      /** @enum {string} */
      kind:
        | "request.arrived"
        | "request.allowed"
        | "request.rejected"
        | "request.bypassed";
      requestId: string;
      nodeId: string;
      message: string;
    };
    RateLimitOutcome: {
      requestId: string;
      nodeId: string;
      /** Format: int64 */
      timeMs: number;
      /** @enum {string} */
      decision: "ALLOWED" | "REJECTED" | "BYPASSED";
      remaining: number;
      /** Format: int64 */
      retryAfterMs?: number | null;
      reason: string;
    };
    RateLimitMetrics: {
      total: number;
      allowed: number;
      rejected: number;
      bypassed: number;
      configuredLimit: number;
      counters: number;
      maximumAggregateAllowance: number;
    };
    RateLimiterResult: {
      /** @constant */
      schemaVersion: "1.0";
      /** @constant */
      simulationId: "distributed-rate-limiter";
      /** @constant */
      modelVersion: "1.0.0";
      /** Format: int64 */
      seed: number;
      /** @constant */
      status: "completed";
      assumptions: string[];
      events: components["schemas"]["RateLimitEvent"][];
      outcomes: components["schemas"]["RateLimitOutcome"][];
      metrics: components["schemas"]["RateLimitMetrics"];
    };
    RateLimiterPreset: {
      id: string;
      title: string;
      question: string;
      input: components["schemas"]["RateLimiterInput"];
    };
    RateLimiterDescriptor: {
      /** @constant */
      id: "distributed-rate-limiter";
      title: string;
      /** @constant */
      kind: "simulation";
      /** @constant */
      modelVersion: "1.0.0";
      description: string;
      limits: {
        [key: string]: number;
      };
      presets: components["schemas"]["RateLimiterPreset"][];
      assumptions: string[];
    };
  };
  responses: never;
  parameters: {
    ContentId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  listTopics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogEntry"][];
        };
      };
    };
  };
  getTopic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TopicDetail"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimulationDescriptor"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  runSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestFlowInput"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RequestFlowResult"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getEstimator: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CapacityEstimatorDescriptor"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  calculateEstimate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ContentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CapacityEstimateInput"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CapacityEstimateResult"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Structured error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getRateLimiterSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RateLimiterDescriptor"];
        };
      };
    };
  };
  runRateLimiterSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RateLimiterInput"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RateLimiterResult"];
        };
      };
      /** @description Structured error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
}
