spring.application.name=hld-with-ui
server.port=${BACKEND_PORT:${SERVER_PORT:8080}}
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.default-property-inclusion=non_null
server.error.include-message=never
